bbuchfink/diamond

src/util/direction.h, src/util/double_buffer.h
This addresses #19 by replacing the GPL license with the BSD license used in other files.
Thanks Benjamin!
=> Use BSD license

src/main.cpp
Return nonzero (1) on "Insufficient arguments" error. 
Issue: https://github.com/bbuchfink/diamond/issues/15
=> Return nonzero on usage error

src/main.cpp
The code introduced in 3660416b9 did always trigger due to missing curly braces.
Signed-off-by: Kai Blin <kblin@biosustain.dtu.dk>
=> Only return 1 when complaning about insufficient arguments

.gitignore, CMakeLists.txt, src/align/align_sequence_anchored.cpp, src/basic/config.h, src/dp/dp.h, src/dp/floating_sw.h, src/output/output_format.cpp
Hi,
You might be interested in these minor edits I had to do to get DIAMOND to compile on Mac OS X 10.11 with GCC 6.1.
- Added -Wno-deprecated-declarations because of auto_ptr
- Explicitely defined set_config for uint64_t
- Manually cast uint64_t as size_t in ostream
- Explicitely code min() for differing types
- Added missing headers
=> Some edits to work with GCC 6.1 on Mac OS X:

build_simple.sh
`cmake` is not part of the xcode stack. `build_simple.sh` works if `-static` is removed as, unfortunately, some of the OSX does not ship with static builds of some of the core libraries. Addresses #74
=> Remove -static to allow compilation on OSX

src/data/reference.cpp
This fixes the build on FreeBSD after a0203d7, but I am not certain it is correct.
=> Fix build error: unknown type name 'ref_header'

src/output/blast_tab_format.cpp
The BLAST tabular style output (output format 6) in DIAMOND supports a set of keywords that are not the same as those supported by BLAST. The [current test](https://github.com/bbuchfink/diamond/blob/master/src/output/blast_tab_format.cpp#L87) for unsupported field names checks against the complete list of possible field names, not all of which are supported.
This patch adds more instructive output to the error messages created when a field that is in `Blast_tab_format::field_str` is chosen but it is not in fact supported (by either `Blast_tab_format::print_match` or `Blast_tab_format::print_query_intro`).
=> Add more detailed errors for invalid output fields

src/search/collision.cpp
Hello Benjamin,
An unpatched 0.9.36 would fail to build with the error: [`/wrkdirs/usr/ports/biology/diamond/work/diamond-0.9.36/src/search/collision.cpp:96:34: error: no member named 'window' in 'Config'`](http://pkg.awarnach.mathstat.dal.ca/data/12amd64-default/2020-07-02_22h01m38s/logs/errors/diamond-0.9.36.log).
After patching, the build finished, but I am unclear of the consequences.
Regards,
Joe
=> Fix build on FreeBSD by removing assert referencing config.window

src/util/system/system.cpp
This fixes a compile error and implements total_ram() on FreeBSD.  The preprocessing is a little more complicated, so I added some whitespace to make the logic clearer.  If this is unwanted, just let me know and I can flatten the #ifdefs.
=> Return total RAM on FreeBSD systems

src/util/system/system.cpp
diamond-2.0.11/src/util/system/system.cpp:198:25:
error: use of undeclared identifier '_SC_LEVEL3_CACHE_SIZE'
const auto s = sysconf(_SC_LEVEL3_CACHE_SIZE);
=> Fix 2.0.11 FreeBSD build

src/align/align.h
The presence of this unimplemented destructor causes linking issues with newer gcc with -O2, and only -O2. Which isn't an issue when BUILD_TYPE is Release, but is when it's RelWithDebInfo. 
Further details are in https://github.com/spack/spack/issues/28295
I tried to report this as a compiler error to my distro, but they were uninterested in something that I couldn't reproduce outside of this code base.
=> Fix weird build error with gcc10+

src/lib/MemoryPool/MemoryPool.tcc, src/util/log_stream.h
One issue popped up when porting workload to other compilers/systems. I will let you know if there are others.
Added explicit #include <cstdint> to enable builds with newer compiler.
=> Fix for gcc-13 build

src/util/string/string.cpp
Hi Benjamin,
This patch allows one to specify sizes to diamond (e.g. for memory usage in deepclust) using T/G/M/K suffixes, rather than only using a G suffix.
Best,
K
=> util/string: Allow T/G/M/K size suffixes

src/util/data_structures/deque.h
Fix build by adding the -= operator to Deque's random access iterator.
Submitted-by: Dimitry Andric <dim@FreeBSD.org>
=> Fix build with clang 17

src/util/log_stream.h
This was causing undefined behavior with the Nvidia NVhpc compiler which eventually led to a segmentatio fault.
=> Fix for uninitialized variable

src/lib/alp/sls_basic.hpp, src/masking/tantan.cpp
Some small performance improvement from safely changing a couple floating point divides to floating point multiplies.
FDIV is more expensive than FMUL on most hardware, but actual improvements will be microarchitecture specific.
=> Change FDIV to FMUL

.github/workflows/cmake.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

src/util/binary_buffer.h
include `<string>` to fix some compile issue as below
```
In file included from /tmp/diamond-20250125-4855-7vw53/diamond-2.1.11/src/basic/packed_transcript.h:21:
/tmp/diamond-20250125-4855-7vw53/diamond-2.1.11/src/util/binary_buffer.h:93:8: error: implicit instantiation of undefined template 'std::basic_string<char>'
dst.push_back(c);
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/iosfwd:248:32: note: template is declared here
class _LIBCPP_TEMPLATE_VIS basic_string;
^
```
relates to https://github.com/Homebrew/homebrew-core/pull/205487
=> fix: include `<string>` in binary_buffer.h for fix macos builds

src/search/finger_print.h
diamond compile failed caused by not explicitly including \<cstring\>.The crucial log is here:
"/build/reproducible-path/diamond-aligner-2.1.11/src/search/finger_print.h:138:17:
error: ‘memcpy’ was not declared in this scope
138 |                 memcpy(r, q - 16, 48);
|                 ^~~~~~
/build/reproducible-path/diamond-aligner-2.1.11/src/search/finger_print.h:26:1:
note: ‘memcpy’ is defined in header ‘<cstring>’; this is probably
fixable by adding ‘#include \<cstring\>’
25 | #include "basic/value.h"
+++ |+#include <cstring>
26 |
"
This issue can be fixed by "#include \<cstring\>"
=> fix gcc error caused by missing include cstring

src/basic/reduction.h, src/basic/seed_iterator.h, src/basic/shape.h, src/basic/value.cpp, src/data/enum_seeds.h, src/data/seed_array.cpp, src/data/seed_set.cpp, src/output/blast_tab_format.cpp, src/search/seed_complexity.cpp, src/search/setup.cpp, src/search/sse_dist.h, src/tools/tools.cpp
The initialization of static variables across different source files depends on each other, leading to undefined behavior because the C++ standard does not guarantee the order of initialization of static variables across different translation units. In this case the problem is happening because Reduction::reduction is being initialized before Stats::blosum62, but Reduction::Reduction is trying to access Stats::blosum62 during its initialization.  The idea is to use a static method that returns a reference to a locally defined static instance of the Reduction class. This ensures that the instance is initialized the first time the method is called I added get/set methods to implement this cleanly.
Error from sanitizer:
```
AddressSanitizer: initialization-order-fiasco on address …
```
=> Fix for sanitizer's initialization-order-fiasco

src/data/taxonomy.cpp, src/data/taxonomy_nodes.h
Fixes #866 and #867
The NCBI taxonomy team have introduced a few more ranks into their database:  https://ncbiinsights.ncbi.nlm.nih.gov/2024/06/04/changes-ncbi-taxonomy-classifications/
This pull-request simply adds the new ranks to the list, keeping the deprecated `superkingdom` rank in to support older dump files.
=> Added the ranks introduced by the NCBI
